// Official LHDN MyInvois e-Invoice Classification Codes
// Source: LHDN MyInvois SDK — Classification Code catalogue.
export const LHDN_CLASSIFICATIONS = [
    { code: "001", description: "Breastfeeding equipment" },
    { code: "002", description: "Child care centres and kindergarten fees" },
    { code: "003", description: "Computer, smartphone or tablet" },
    { code: "004", description: "Consolidated e-Invoice" },
    { code: "005", description: "Construction materials (as specified under the Fourth Schedule of the Lembaga Pembangunan Industri Pembinaan Malaysia Act 1994)" },
    { code: "006", description: "Disbursement" },
    { code: "007", description: "Donation" },
    { code: "008", description: "e-Commerce - e-Invoice to buyer / purchaser" },
    { code: "009", description: "e-Commerce - Self-billed e-Invoice to seller, logistics, etc." },
    { code: "010", description: "Education fees" },
    { code: "011", description: "Goods on consignment (Consignor)" },
    { code: "012", description: "Goods on consignment (Consignee)" },
    { code: "013", description: "Gift card, voucher (Digital or physical)" },
    { code: "014", description: "Interest and financing charges" },
    { code: "015", description: "Internet subscription" },
    { code: "016", description: "Land and building" },
    { code: "017", description: "Medical examination for employees" },
    { code: "018", description: "Medical examination or vaccination expenses" },
    { code: "019", description: "Medical expenses for serious diseases" },
    { code: "020", description: "Motor vehicle" },
    { code: "021", description: "Others" },
    { code: "022", description: "Petroleum operations (as defined in Petroleum (Income Tax) Act 1967)" },
    { code: "023", description: "Private retirement scheme or Deferred Annuity Scheme" },
    { code: "024", description: "Motor vehicle repair and maintenance" },
    { code: "025", description: "Subscription of books / journals / magazines / newspapers / other similar publications" },
    { code: "026", description: "Reimbursement" },
    { code: "027", description: "Rental of motor vehicle" },
    { code: "028", description: "Rental of personal computer and similar personal devices" },
    { code: "029", description: "Rental of telecommunication equipment" },
    { code: "030", description: "Repair and maintenance" },
    { code: "031", description: "Research and development" },
    { code: "032", description: "Foreign income" },
    { code: "033", description: "Self-billed - Betting and gaming" },
    { code: "034", description: "Self-billed - Importation of goods" },
    { code: "035", description: "Self-billed - Importation of services" },
    { code: "036", description: "Self-billed - Others" },
    { code: "037", description: "Self-billed - Monetary payment to agents, dealers or distributors" },
    { code: "038", description: "Sports equipment, rental / lease of sports equipment, sports training and competition fees" },
    { code: "039", description: "Supporting equipment for disabled person" },
    { code: "040", description: "Voucher" },
    { code: "041", description: "Traditional and complementary medicine, and preventive treatments" },
    { code: "042", description: "Vouchers, gift cards, loyalty points, etc." },
    { code: "043", description: "Dental examination including dental treatment" },
    { code: "044", description: "Fertility treatment" },
    { code: "045", description: "Vaccination" },
];
