// UN/ECE Recommendation 20 — common measurement units used in LHDN e-Invoice.
export const MEASUREMENT_CODES = [
    { code: "10", description: "group" },
    { code: "11", description: "outfit" },
    { code: "13", description: "ration" },
    { code: "14", description: "shot" },
    { code: "15", description: "stick, military" },
    { code: "1I", description: "fixed rate" },
    { code: "20", description: "twenty foot container" },
    { code: "21", description: "forty foot container" },
    { code: "22", description: "decilitre" },
    { code: "23", description: "gram per cubic centimetre" },
    { code: "25", description: "days" },
    { code: "27", description: "theoretical ton" },
    { code: "28", description: "kilogram per square metre" },
    { code: "33", description: "kilopascal square metre per gram" },
    { code: "34", description: "kilopascal per millimetre" },
    { code: "35", description: "millilitre per square centimetre second" },
    { code: "37", description: "ounce per square foot" },
    { code: "38", description: "ounce per square foot per 0,01 inch" },
    { code: "40", description: "millilitre per second" },
    { code: "41", description: "millilitre per minute" },
    { code: "56", description: "sitas" },
    { code: "57", description: "mesh" },
    { code: "58", description: "net kilogram" },
    { code: "59", description: "part per million (ppm)" },
    { code: "60", description: "percent weight" },
    { code: "61", description: "part per billion (US)" },
    { code: "74", description: "millipascal" },
    { code: "77", description: "milli-inch" },
    { code: "80", description: "pound per square inch, absolute" },
    { code: "81", description: "henry" },
    { code: "85", description: "foot pound-force" },
    { code: "89", description: "poise" },
    { code: "91", description: "stokes" },
    { code: "94", description: "percent" },
    { code: "95", description: "parts per thousand" },
    { code: "96", description: "pound-force per square inch" },
    { code: "97", description: "psi per square inch" },
    { code: "AS", description: "assortment" },
    { code: "BB", description: "base box" },
    { code: "BE", description: "bundle" },
    { code: "BG", description: "bag" },
    { code: "BJ", description: "bucket" },
    { code: "BK", description: "basket" },
    { code: "BL", description: "bale" },
    { code: "BO", description: "bottle" },
    { code: "BX", description: "box" },
    { code: "CA", description: "can" },
    { code: "CH", description: "container" },
    { code: "CL", description: "coil" },
    { code: "CMK", description: "square centimetre" },
    { code: "CMQ", description: "cubic centimetre" },
    { code: "CMT", description: "centimetre" },
    { code: "CR", description: "crate" },
    { code: "CS", description: "case" },
    { code: "CT", description: "carton" },
    { code: "CX", description: "coffee sacks" },
    { code: "DAY", description: "day" },
    { code: "DMT", description: "decimetre" },
    { code: "DOZ", description: "dozen" },
    { code: "DPC", description: "dozen pieces" },
    { code: "DPR", description: "dozen pairs" },
    { code: "DR", description: "drum" },
    { code: "DZN", description: "dozen" },
    { code: "EA", description: "each" },
    { code: "FT", description: "foot" },
    { code: "GLL", description: "gallon (US)" },
    { code: "GRM", description: "gram" },
    { code: "GRO", description: "gross" },
    { code: "GT", description: "gross ton" },
    { code: "HR", description: "hour" },
    { code: "IN", description: "inch" },
    { code: "JR", description: "jar" },
    { code: "KG", description: "kilogram" },
    { code: "KGM", description: "kilogram" },
    { code: "KM", description: "kilometre" },
    { code: "KWH", description: "kilowatt hour" },
    { code: "LBR", description: "pound" },
    { code: "LTR", description: "litre" },
    { code: "MC", description: "microgram" },
    { code: "MGM", description: "milligram" },
    { code: "MIN", description: "minute" },
    { code: "MLT", description: "millilitre" },
    { code: "MMT", description: "millimetre" },
    { code: "MO", description: "month" },
    { code: "MTK", description: "square metre" },
    { code: "MTQ", description: "cubic metre" },
    { code: "MTR", description: "metre" },
    { code: "NAR", description: "number of articles" },
    { code: "NPR", description: "number of pairs" },
    { code: "OZA", description: "fluid ounce" },
    { code: "OZI", description: "ounce" },
    { code: "PA", description: "packet" },
    { code: "PCE", description: "piece" },
    { code: "PK", description: "package" },
    { code: "PR", description: "pair" },
    { code: "RL", description: "reel" },
    { code: "RO", description: "roll" },
    { code: "SET", description: "set" },
    { code: "T3", description: "thousand piece" },
    { code: "TNE", description: "tonne (metric ton)" },
    { code: "TU", description: "tube" },
    { code: "UNIT", description: "unit" },
    { code: "WEE", description: "week" },
    { code: "YRD", description: "yard" },
];
